### ISSUE TITLE
Verify the configuration of each course before deploy 

### ISSUE THREAD

**Issue by anandology** [fossunited/monschool-website#12]
Every course has a `course.yml` file and markdown file for each lesson has yaml frontmatter. If there is any error in these files, the deploy fails. We want to verify this on every PR and fail.

## Interface

The verification process will be triggered by running the `lint` command. It should test for each possible error, report all errors and fail with non-zero exit code if any issue is found.

```
$ python manage.py lint
```

## Tasks

- [ ] implement `lint` command
- [ ] verify the correctness of course.yml file in each course
- [ ] verify the frontmatter of each lesson is valid

**Comment by anandology** [comment]
It may be a good idea to this using pytest. There could be a test_website directory with all the tests.

**Comment by anandology** [comment]
Tried writing test cases. It feels like having a linter a good idea and it'll allow us to test the linter as well.
